# Configuration file for Alticast Xconf Log Server.

# Alticast Xconf Log Server configuration.
logserver:
    port: 8080
    destination: "file:///opt/logserver/logs"
    encode: false

# Cassandra DB configuration.
cassandra:
    hosts: [
        "172.18.0.2"
    ]
