# Configuration file for Xconf Log Server.

# Xconf Log Server configuration.
logserver:
    port: 8080
    destination: "file:///opt/logserver/logs"
    encode: false
    log:
        file: "/opt/logserver/logs/logserver.log"
        enable: true
        debug: true
        info: true
        warn: true
        error: true


# Cassandra DB configuration.
cassandra:
    hosts: [
        "172.18.0.2"
    ]
    reconnection:
        tries: 10
        interval: 5
    keyspace: "LogDataService"
